name: Hello world

on:
  push: #Event name
    branches: #Where to listen the event
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: hello world
        run: echo "hello world"
        shell: bash
      - name: List Files in Repository
        run: ls -R $GITHUB_WORKSPACE | grep -vE 'node_modules|dist'


      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.2.0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: version
        uses: gittools/actions/gitversion/execute@v1.2.0

      - name: Print version
        run: echo "version ${{ steps.version.outputs}}"

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "goodbye world"
        shell: bash
#Jons runs in parallel
